{% set name = "azure-mgmt-authorization" %}
{% set version = "5.0.0b1" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_')}}-{{ version }}.tar.gz
  sha256: 2b96eab3a61ef9dd84776a476482e82726013bfe110262d90619685b235e5737

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv
  skip: true  # [py<39]

requirements:
  host:
    - python
    - pip
    - wheel
    - setuptools
  run:
    - python
    - isodate >=0.6.1
    - typing-extensions >=4.6.0
    - azure-common >=1.1
    - azure-mgmt-core >=1.5.0

test:
  imports:
    - azure.mgmt.authorization
    - azure.mgmt.authorization.aio
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/Azure/azure-sdk-for-python
  summary: Microsoft Azure Authorization Management Client Library for Python
  license: MIT
  license_family: MIT
  license_file: LICENSE
  description: Microsoft Azure Authorization Management Client Library for Python
  doc_url: https://github.com/Azure/azure-sdk-for-python
  dev_url: https://github.com/Azure/azure-sdk-for-python

extra:
  recipe-maintainers:
  - andreyz4k
