travis:
  secure:
    BINSTAR_TOKEN: rj4Uq2Yty1TJTR0O9XKhzq82PDKq/fUee6WmLMoSqvtdO9FjNswiAkagQwwNTCSDV6Xm67o1oHdlZIw7M5fC2wW8b1dBjug8nYNWTU8ASx4wiIdu9lGykYV8/4OrmC5DrEd1mCAl6uc0UQuLjWfyUyzDLkp2XzfkgY9vVSBiQ2SrR6i8cKBAu+BbNAiM7jJ+kKT4IJ2BIrlj/yA1crdUxmflsAcGfMPfCTh3vsmmX45yxXnRPMeKSQof5AWiFmumBQwmUww0iy/0/Hd1Sa2SWNOuWeZEghB5BuQoPmzS0OjOdZycoRPOYOoxI4PjwL2xgn/NTbbGXK2rJSl3LaAqEnTYSalAgZ213dleg06UZr7BZKCMub0a8x2NlFWTkz8d+VSyaTbzXVVBp5ffyTmQCFhlK46TPqERW4G1B/ZNVphHz3r0R0QjqhYVhQx1dd93C4j17gbdEwFodBib6E0c2FJCr9UbETO49GzivvU1+XqY28C6Mtwn5YTCpg8Xzjs/eaiw2WoDv3dHa2fvFXgUPkAKsvv+DIWYm01SLOojT63VTpHM3PmblNC5SU17/kVxJWyqBgwldowrN3dD2vvIfOWJMvdsgSeAeQobkTSEjAkqGKdHA1ntvwPB8Ms54V0HwWxlkvdvsa0grm3qsrdy+93WzDCoaMlvPIMgFOfTMHI=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
